stepback: true

command_type: system

ignore:
  - /.evergreen/dependencies
  - /.evergreen/toolchain

exec_timeout_secs: 1800

timeout:
  - command: shell.exec
    params:
      script: ls -la

functions:
  "buildModule" :
    command: shell.exec
    type: test
    params:
      script: |
        ${prepare_shell}
        $PERL ${repo_directory}/.evergreen/testing/build.pl

  "cleanUp":
    command: shell.exec
    params:
      script: |
        ${prepare_shell}
        rm -rf ~/.cpanm
        rm -rf perl5
        rm -rf ${repo_directory}

  "downloadBuildArtifacts" :
    - command: s3.get
      params:
        bucket: mciuploads
        aws_key: ${aws_key}
        aws_secret: ${aws_secret}
        remote_file: ${aws_artifact_prefix}/${repo_directory}/${build_id}/build.tar.gz
        local_file: ${repo_directory}/build.tar.gz
    - command: shell.exec
      params:
        script: |
          ${prepare_shell}
          cd ${repo_directory}
          tar -zxf build.tar.gz

  "downloadPerl5Lib" :
    - command: s3.get
      params:
        bucket: mciuploads
        aws_key: ${aws_key}
        aws_secret: ${aws_secret}
        remote_file: ${aws_toolchain_prefix}/${os}/${perlver}/${target}/perl5lib.tar.gz
        local_file: perl5lib.tar.gz
    - command: shell.exec
      params:
        script: |
          ${prepare_shell}
          tar -zxf perl5lib.tar.gz

  "dynamicVars":
    - command: shell.exec
      params:
        script: |
            set -o errexit
            set -o xtrace
            cat <<EOT > expansion.yml
            prepare_shell: |
                export PATH="${addpaths}:$PATH"
                export PERL="${perlpath}"
                export REPO_DIR="${repo_directory}"
                set -o errexit
                set -o xtrace
            EOT
            cat expansion.yml
    - command: expansions.update
      params:
        file: expansion.yml

  "fetchSource" :
    - command: git.get_project
      params:
        directory: src
    - command: shell.exec
      params:
        script: |
          ${prepare_shell}
          mv src ${repo_directory}

  "testDriver" :
    command: shell.exec
    type: test
    params:
      script: |
        ${prepare_shell}
        export MONGOD=$(echo "${MONGODB_URI}" | tr -d '[:space:]')
        export PERL_MONGO_WITH_ASSERTS=${assert}
        export PERL_BSON_BACKEND="${bsonpp}"
        SSL=${ssl} $PERL ${repo_directory}/.evergreen/testing/test.pl

  "testLive" :
    command: shell.exec
    type: test
    params:
      script: |
        ${prepare_shell}
        set +x
        echo "export MONGOD=<redacted>"
        export MONGOD="${uri}"
        set -x
        $PERL ${repo_directory}/.evergreen/testing/live-test.pl

  "uploadBuildArtifacts":
    - command: s3.put
      params:
        aws_key: ${aws_key}
        aws_secret: ${aws_secret}
        local_file: ${repo_directory}/build.tar.gz
        remote_file: ${aws_artifact_prefix}/${repo_directory}/${build_id}/build.tar.gz
        bucket: mciuploads
        permissions: public-read
        content_type: application/x-gzip

  "whichPerl":
    command: shell.exec
    params:
      script: |
        ${prepare_shell}
        $PERL -v

post:
  - func: cleanUp

tasks:
  - name: build
    commands:
      - func: dynamicVars
      - func: cleanUp
      - func: fetchSource
      - func: downloadPerl5Lib
        vars:
          target: '${repo_directory}'
      - func: whichPerl
      - func: buildModule
      - func: uploadBuildArtifacts
  - name: check
    commands:
      - func: dynamicVars
      - func: cleanUp
      - func: fetchSource
      - func: downloadPerl5Lib
        vars:
          target: '${repo_directory}'
      - func: whichPerl
      - func: downloadBuildArtifacts
      - func: testDriver
    depends_on:
      - name: build
  - name: test_atlas_free
    commands:
      - func: dynamicVars
      - func: cleanUp
      - func: fetchSource
      - func: downloadPerl5Lib
        vars:
          target: '${repo_directory}'
      - func: whichPerl
      - func: downloadBuildArtifacts
      - func: testLive
        vars:
          uri: '${atlas_free}'
    depends_on:
      - name: check
  - name: test_atlas_replica
    commands:
      - func: dynamicVars
      - func: cleanUp
      - func: fetchSource
      - func: downloadPerl5Lib
        vars:
          target: '${repo_directory}'
      - func: whichPerl
      - func: downloadBuildArtifacts
      - func: testLive
        vars:
          uri: '${atlas_replica}'
    depends_on:
      - name: check
  - name: test_atlas_sharded
    commands:
      - func: dynamicVars
      - func: cleanUp
      - func: fetchSource
      - func: downloadPerl5Lib
        vars:
          target: '${repo_directory}'
      - func: whichPerl
      - func: downloadBuildArtifacts
      - func: testLive
        vars:
          uri: '${atlas_sharded}'
    depends_on:
      - name: check
  - name: test_atlas_tls11
    commands:
      - func: dynamicVars
      - func: cleanUp
      - func: fetchSource
      - func: downloadPerl5Lib
        vars:
          target: '${repo_directory}'
      - func: whichPerl
      - func: downloadBuildArtifacts
      - func: testLive
        vars:
          uri: '${atlas_tls11}'
    depends_on:
      - name: check
  - name: test_atlas_tls12
    commands:
      - func: dynamicVars
      - func: cleanUp
      - func: fetchSource
      - func: downloadPerl5Lib
        vars:
          target: '${repo_directory}'
      - func: whichPerl
      - func: downloadBuildArtifacts
      - func: testLive
        vars:
          uri: '${atlas_tls12}'
    depends_on:
      - name: check

buildvariants:
  - name: os_ubuntu1604_perl_24
    display_name: Ubuntu 16.04 x86_64 Perl 5.24
    expansions:
      addpaths: /opt/perl/24/bin
      os: ubuntu1604
      perlpath: /opt/perl/24/bin/perl
      perlver: 24
    run_on:
      - ubuntu1604-test
    tasks:
      - build
      - check
      - test_atlas_free
      - test_atlas_replica
      - test_atlas_sharded
      - test_atlas_tls11
      - test_atlas_tls12
